// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk8KEo4HLUeM6HDu-srK6z-0dftJ1IW_w',
    appId: '1:982755619351:web:215f20d9685392a02b2252',
    messagingSenderId: '982755619351',
    projectId: 'taskerr-1',
    authDomain: 'taskerr-1.firebaseapp.com',
    storageBucket: 'taskerr-1.firebasestorage.app',
    measurementId: 'G-WDFHD6WBX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLa6_G6ht4TW7aHYDBziOifH4i9BjH0sg',
    appId: '1:982755619351:android:9825d468480551da2b2252',
    messagingSenderId: '982755619351',
    projectId: 'taskerr-1',
    storageBucket: 'taskerr-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2j_sotVwQlSCB0GLPwPOJr-bLBh_spqo',
    appId: '1:982755619351:ios:b55e7ddd119a572c2b2252',
    messagingSenderId: '982755619351',
    projectId: 'taskerr-1',
    storageBucket: 'taskerr-1.firebasestorage.app',
    iosBundleId: 'com.example.taskerr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2j_sotVwQlSCB0GLPwPOJr-bLBh_spqo',
    appId: '1:982755619351:ios:b55e7ddd119a572c2b2252',
    messagingSenderId: '982755619351',
    projectId: 'taskerr-1',
    storageBucket: 'taskerr-1.firebasestorage.app',
    iosBundleId: 'com.example.taskerr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk8KEo4HLUeM6HDu-srK6z-0dftJ1IW_w',
    appId: '1:982755619351:web:156bc701860bf0902b2252',
    messagingSenderId: '982755619351',
    projectId: 'taskerr-1',
    authDomain: 'taskerr-1.firebaseapp.com',
    storageBucket: 'taskerr-1.firebasestorage.app',
    measurementId: 'G-VCL50477MN',
  );
}
